on:
  workflow_dispatch:  
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04
    steps:
      - name: chdckout repo
        uses: actions/checkout@v4
      - name: checkout python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.10
      - name: run script
        run:  echo "esto es el repositorio $GITHUB_REPOSITORY"
